# Generated by Django 4.1.1 on 2022-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_admin', '0002_alter_ingredient_options_alter_ingredient_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
