# Generated by Django 4.1.1 on 2022-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_admin', '0003_meal_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно к показу'),
        ),
    ]
