# Generated by Django 4.1.1 on 2022-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_admin', '0004_alter_meal_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals'),
        ),
    ]
